### ISSUE TITLE
DevOps vs SRE

### ISSUE THREAD

**Issue by yardensachs** [helpfulengineering/devops#1]
### About
One of the items that was brought up in our last conversation was the term SRE being more fitting for the team/efforts. This was not addressed since and when I wanted to start writing some into documentation, I was confronted with this question first.

### Call to action
Not being a DevOps eng or SRE, I don't think I can make the call here.
It would be great if there was a 1-3 day conversation here to document the decision on this here:
Should this remain as "DevOps" or should we change the name to SRE as suggested once?

I know this is not an important issue, but this is good practice for us to document decisions in github and create a culture based on conversations and collaboration.

**Comment by imonthercks** [comment]
While I am still coming up to speed on the workings of this team/group, I would agree that this team is more of an enabling or SRE type team, meaning its purpose is to get projects off the ground with reasonably good security, scalability and observability practices in place, not to mention automation, testing and good coding practices.  That said, there could really be two types of teams formed out of this group, where one group would be more of an enabling SRE type team and another could be more of a platform or architecture type team that maintains those things that are shared amongst the different product teams that make it easier to meet the goals of security, scalability and observability.  Some examples of this could be a shared monitoring platform, shared ci/cd platform, shared cdk/cft/tf templates or packages that ensures sane defaults are being used across all software products.  The benefit of a separate platform team from SREs that work alongside product teams is that the platform team can focus on the platform as a product, ensuring that that product is delivered in a consistent and always compatible manner.  And all of this, including product teams, really falls under the DevOps umbrella, as DevOps is more about practice and culture than team structure, so I would agree that moving away from being a DevOps team makes sense.  I really hope this all made sense and is helpful. 😀

**Comment by dmangot** [comment]
The idea that this is called the DevOps team makes me wretch as I'm an internationally recognized member of the DevOps movement in the sense that @imonthercks refers to it.  That said, this organization is having enough trouble at the moment getting its feet underneath it, and it's getting better at that every day, so this seem like something we could revisit in the future.
