### ISSUE TITLE
Repository request: [Project Tetra Display]

### ISSUE THREAD

**Issue by fpdotmonkey** [helpfulengineering/devops#71]
## I would like to...
- [x] Import an existing repository
- [ ] Create a new repository

## The current address of my repository is...
https://github.com/fpdotmonkey/SplitterStaging

## The Slack channel of the project is...
#project-tetra

## I want to license the data under...

- [ ] Hardware and/or firmware: CERN-OHL-P
- [x] Software: Apache License, Version 2.0
- [ ] Guides, instructional videos, and other materials: Creative Commons Attribution 4.0

**Source:** [official licensing guide](/documentation/license-guide.md)

**Comment by 0x2b3bfa0** [comment]
Could this be included inside the main [project-tetra](https://github.com/helpfulengineering/project-tetra) repository? It can be seamlessly merged while preserving commit history.

**Comment by fpdotmonkey** [comment]
Ah yeah makes sense.  I'll do that.
