### ISSUE TITLE
Repository request: [project-licence]

### ISSUE THREAD

**Issue by Jbutler-helpful** [helpfulengineering/devops#85]
## I would like to...
- [] Import an existing repository
- [ x] Create a new repository

## I want to license the data under...

- [ ] Hardware and/or firmware: CERN-OHL-P
- [ ] Software: Apache License, Version 2.0
- [ ] Guides, instructional videos, and other materials: Creative Commons Attribution 4.0
- [x ] outstanding question

**Source:** [official licensing guide](/documentation/guidance/project-licensing.md)

**Comment by 0x2b3bfa0** [comment]
https://github.com/helpfulengineering/project-licence
