### ISSUE TITLE
Repository request: [project-deelgo]

### ISSUE THREAD

**Issue by usyoudev** [helpfulengineering/devops#86]
## I would like to...
- [] Import an existing repository
- [x] Create a new repository

## The Slack channel of the project is...
project-deelgo

## I want to license the data under...

- [] Hardware and/or firmware: CERN-OHL-P
- [x] Software: Apache License, Version 2.0
- [ ] Guides, instructional videos, and other materials: Creative Commons Attribution 4.0

**Source:** [official licensing guide](/documentation/guidance/project-licensing.md)

**Comment by 0x2b3bfa0** [comment]
https://github.com/helpfulengineering/project-deelgo
